#!/bin/bash

######################################################################
# testheapimp_add tests a single heapmgr implementation.
# All test cases satisfy (number of cells) x (size in bytes) ≤10^9
######################################################################

# Validate the argument.
if [ "$#" -ne "1" ]; then
   echo "Usage: testheapimp [executablefile]"
   exit 1
fi

# Capture the argument.
executablefile=$1

echo "=============================================================================="
$executablefile LIFO_fixed 100000 1000
$executablefile FIFO_fixed 100000 1000
$executablefile LIFO_random 100000 1000
$executablefile FIFO_random 100000 1000
$executablefile random_fixed 100000 1000
$executablefile random_random 100000 1000
echo "=============================================================================="
$executablefile LIFO_fixed 100000 10000
$executablefile FIFO_fixed 100000 10000
$executablefile LIFO_random 100000 10000
$executablefile FIFO_random 100000 10000
$executablefile random_fixed 100000 10000
$executablefile random_random 100000 10000
echo "=============================================================================="
$executablefile LIFO_fixed 200000 5000
$executablefile FIFO_fixed 200000 5000
$executablefile LIFO_random 200000 5000
$executablefile FIFO_random 200000 5000
$executablefile random_fixed 200000 5000
$executablefile random_random 200000 5000
echo "=============================================================================="
$executablefile LIFO_fixed 500000 2000
$executablefile FIFO_fixed 500000 2000
$executablefile LIFO_random 500000 2000
$executablefile FIFO_random 500000 2000
$executablefile random_fixed 500000 2000
$executablefile random_random 500000 2000
echo "=============================================================================="
$executablefile LIFO_fixed 1000000 1000
$executablefile FIFO_fixed 1000000 1000
$executablefile LIFO_random 1000000 1000
$executablefile FIFO_random 1000000 1000
$executablefile random_fixed 1000000 1000
$executablefile random_random 1000000 1000
echo "=============================================================================="
$executablefile LIFO_fixed 1000000 100
$executablefile FIFO_fixed 1000000 100
$executablefile LIFO_random 1000000 100
$executablefile FIFO_random 1000000 100
$executablefile random_fixed 1000000 100
$executablefile random_random 1000000 100